### ISSUE TITLE
Files greater than 5GB~ can not be downloaded

### ISSUE THREAD

**Issue by mOrfiUs** [tonikelope/megacrypter#1]
I dont know if it is a problem of implementation or by design but:
FILE SIZE 5200474988
http://youpaste.co/!TZQEGvy7u900AHl08ANlpQeWQ-OTQGVOe0uhkj8smh3GQlF9PStOFs5ihPo9NFkkXIM-XAFJY6eeqRRSpqGQUa_1mpunkRyXxxe-mt1gYTEQerx9NsjgVG_CNnCVlGWh!21c7cd19
can be downloaded without problem

FILE SIZE 5209705116
http://youpaste.co/!MFH66DsZXbu4ZGvSxgoJEfMALrEjn1_-2T8VmJimR6J01DyNcDUUpNsptAoIHdorkVAuCz5UoqXDzIBwI8y_Zhe4Fna4ymD_pvqFn7soQ_cfWCqvPZYP8u1pWNQWLr9L!e92e4e93
can't be downloaded (Megadownloader and JD2)

I can do more test, if you need other data.

Thanks in advanced.

Gracias por Megacrypter. Excepcional trabajo.

**Comment by tonikelope** [comment]
I can download both files with https://github.com/tonikelope/megabasterd 

Salu2 ;)

**Comment by mOrfiUs** [comment]
Sorry, in the first post  the second file size is < 5GB
Can you try this one? This one is >5GB
Megabasterd can't donwload it

FILE SIZE 5444014562
http://youpaste.co/!80qzF7fqt5QYBaSLsPboQNWco5lQ81Q_ha6quY8G5_FLwyZegJPREka_8qY0cuETyCdX_FPegp2-XEGqIXn-KvWE7VFMqktva281Ocrbmsc6Eyk40UQYqs0o5xmix39o!63249be9

Gracias de antemano.

**Comment by tonikelope** [comment]
The last link returns ERROR 509: Bandwidth Limit Exceeded 

This error is due to a MEGA on per FILE and IP limitation. youpaste.co MUST update its MegaCrypter installation in order to skip it (for now).

Salu2 ;)

**Comment by mOrfiUs** [comment]
De acuerdo, eso me parecía. Intentaré pasarte algunas incidencias de Megabasterd, que por cierto funciona bastante rápido. En su hilo, claro.
Saludos y gracias!!
